language: ruby
rvm:
  - 2.2.2
addons:
  postgresql: "9.3"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get upgrade -qq
  - sudo apt-get install -qq google-chrome-stable

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp your_story/config/database.yml.travis your_story/config/database.yml
  - cd your_story/client
  - npm install
  - cd ..
  - bundle install
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rake --trace db:seed
  - cd ..

script:
  - cd your_story
  - bundle exec rake spec
  - cd client
  - npm run db
  - npm run test
