default: &default
  adapter: sqlite3
  # encoding: unicode
  # host: localhost
  # port: 5432
  pool: 1
  timeout: 200

development:
  <<: *default
  database: db/aiesec_data_development.sqlite3
  username: aiesec_data
  password: aiesec
  min_messages: warning

test:
  <<: *default
  database: db/aiesec_data_testing.sqlite3
  username: aiesec_data
  password: aiesec
  min_messages: warning

production:
  <<: *default
  database: db/aiesec_data.sqlite3