default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 1
  timeout: 200

development:
  <<: *default
  database: aiesec_data_development
  username: aiesec_data
  password: aiesec
  min_messages: warning

test:
  <<: *default
  database: aiesec_data_testing
  username: aiesec_data
  password: aiesec
  min_messages: warning

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>